source 'https://github.com/CocoaPods/Specs.git'

target 'componentsOC_Example' do
  pod 'componentsOC', :path => '../'
end

target 'componentsOC_Tests' do
    inherit! :search_paths
    pod 'componentsOC', :path => '../'
end
